### ISSUE TITLE
Modulbrowser hängt sich auf

### ISSUE THREAD

**Issue by emb-laube** [emb-laube/pwa#1]
Wenn man zu einer Präsentation ein Modul hinzugefügt hat und anschließend ein weiteres Modul hinzufügen möchte, dass reagiert der Modulbrowser nicht. Man muss zuerst auf den Templatebrowser wechseln und zurück damit der Modulbrowser wieder funktioniert.

**Comment by emb-laube** [comment]
Done!

**Comment by emb-baran** [comment]
checked!
