### ISSUE TITLE
ZOOM in/out Listenpunkte verschieben sich

### ISSUE THREAD

**Issue by emb-laube** [emb-laube/pwa#10]
Wenn man auf einer Folie ein Textelement mit einer Liste hat und den Browser zoomt mit STRG-+, dann verschiebt sich die Liste innerhalb des Textelements.

**Comment by emb-laube** [comment]
Element wird deselktiert bevor der Browser zoomt!

**Comment by emb-baran** [comment]
checked aber komische Ladesymbole mit gestrichelter Umrandung innerhalb der Präsentation im Online-View

**Comment by emb-laube** [comment]
hat das was mit dem Zoom zu tuen oder ist das ein neuer Issue?

**Comment by timemb** [comment]
Bug besteht weiterhin, element ist immernoch selektiert und tippen ist auch weiterhin möglich. 
TinyMCE Editor verschiebt sich aus dem ausgewählten Feld des Elements.

**Comment by emb-laube** [comment]
Brauchen wir diese Zoom-Funktion überhaupt?

**Comment by emb-laube** [comment]
Done!
