### ISSUE TITLE
Elemente in den Modulen locken

### ISSUE THREAD

**Issue by emb-baran** [emb-laube/pwa#100]
- Macht es Sinn Elemente in den Modulen zu locken? - Angenommen Es werden Vortragsunterlagen in der Präsentation zusammengeklickt, und es muss nur noch der Name des Präsentierenden geändert werden…In diesem Fall würde ich alle Inhaltlichen Elemente in den Modulen locken ausser in diesem Beispiel den Namen...

**Comment by emb-laube** [comment]
Done!
