### ISSUE TITLE
Virencheck?

### ISSUE THREAD

**Issue by timemb** [emb-laube/pwa#105]
Wasn wenn von intern (also dem Unternehmen selber) Viren beim Upload in den Mediabrowser hochgeladen wird??

**Comment by emb-laube** [comment]
http://stackoverflow.com/questions/10660260/what-are-my-options-to-check-for-viruses-on-a-php-upload

**Comment by emb-laube** [comment]
Wird serverseitig vom Server-Betriebssystem erledigt!
