### ISSUE TITLE
Layerübersicht

### ISSUE THREAD

**Issue by emb-baran** [emb-laube/pwa#127]
es wäre cool, wenn man bei der Erstellung der Templates eine Übersicht anzeigen lassen könnte, welche Layer alles verwendet werden. Also z.B.:
1. Hintergrundbild.jpg - Bild
2. EInführung - Text
3. Rahmen - Shape

dann wäre es gut wenn man einzelen auswählen könnte zur Bearbeitung.

**Comment by emb-laube** [comment]
Siehe #15
