### ISSUE TITLE
Template Dimensionen können vermischt werden

### ISSUE THREAD

**Issue by emb-laube** [emb-laube/pwa#13]
Legt man ein Modul an beginnend mit 16:9, dann sollte es nicht möglich sein eine neue Folie in einem anderen Format hinzuzufügen

**Comment by emb-laube** [comment]
Module kennen die Information über ihr Format nicht, dass muss in der DB angelegt werden. Erst dann kann der Modulbrowser die Anzeige entsprechend Filtern.

**Comment by emb-laube** [comment]
Done!

**Comment by emb-baran** [comment]
checked
wir sollten den Hinweis dazu irgendwo hinterlegen das ein Format gewählt wurde. Sonst wundert man sich warum die anderen Vorlagen einfach nicht mehr angezeigt werden.
