### ISSUE TITLE
Individualisierbare Listenpunkte

### ISSUE THREAD

**Issue by timemb** [emb-laube/pwa#145]
Listenpunkte individualisierbar pro Text-Style

**Comment by emb-laube** [comment]
So ich hab ein wenig recherchiert:
Wir können das Listenpunkt-Zeichen verändern, aber nicht völlig frei.
Wir können die Schriftart und das Zeichen bestimmen, nicht aber die Farbe oder die Größe des Zeichens. Eine Durchnummerierung wäre auch möglich. Ein Icon (also eine Grafik) können wir nicht verwenden.
@timemb Was schlägst du vor sollen wir also machen?

**Comment by emb-laube** [comment]
Listen als eigenes Textelement machen
Ähnlich zu TextStyles zusätzlich ListStyles anlegen
