### ISSUE TITLE
Textsyle Error beim Anlegen 

### ISSUE THREAD

**Issue by timemb** [emb-laube/pwa#146]
Ablauf:
in Textformate klick auf "Neues Textformat anlegen" -> neues textformat wird erstellt
Änderungen/anpassungen an gewünschtes Textformat (Schriftgröße etc.), anschließend speichern -> Fehler "Textstyle does not exist ErrorId: 9504

(siehe Screenshot)

Workaround:
aus Textformat in einen anderen Bereich wechseln, und dann wieder zurück zu den Textformaten und der neue Textstyle lässt sich anpassen und speichern und löschen etc.

![error-textstyles](https://cloud.githubusercontent.com/assets/13312142/11719404/dfc19c4a-9f5a-11e5-8fec-9806660640be.png)

**Comment by emb-laube** [comment]
Fixed
