### ISSUE TITLE
Bildupload innerhalb des Templatebaus nicht möglich

### ISSUE THREAD

**Issue by timemb** [emb-laube/pwa#151]
Beim Bau eines Templates auf "Medien-Werkzeug" geklickt.
Im Mediabrowser den Ordner ausgewählt, und der Upload eines Bildes an dieser Stelle führt zu einem Fehler.

Workaround: Medienbrowser aus dem Dashboard aufrufen und Bild hochladen.

![fehlerupload](https://cloud.githubusercontent.com/assets/13312142/11785378/d6635222-a281-11e5-965f-acf30881c0ca.jpg)

**Comment by emb-laube** [comment]
Fehler im alten PHP Script. Gewechselt auf neues Upload Script. -> Funktioniert!
