### ISSUE TITLE
Anmeldename wird nicht angezeigt in Userverwaltung

### ISSUE THREAD

**Issue by emb-thomas** [emb-laube/pwa#154]
![keineanmeldename](https://cloud.githubusercontent.com/assets/16306707/11815205/06c4c3d2-a34b-11e5-8622-29c4f8a96a1e.jpg)

**Comment by emb-laube** [comment]
Du hast dir keinen Anzeigenamen bei der Anmeldung gegeben ...
Hab das korrigiert und falls das jemand in Zukunft macht, dann wird der username angezeigt.
