### ISSUE TITLE
Sonderzeichen nicht möglich

### ISSUE THREAD

**Issue by emb-thomas** [emb-laube/pwa#155]
![sonderzeichen](https://cloud.githubusercontent.com/assets/16306707/11815262/3d5d1a16-a34b-11e5-8650-0e2d3999b215.jpg)

**Comment by emb-laube** [comment]
Jap ist im alten Editor so, weil ich da noch nicht genau wusste wie ich die Sonderzeichen encodieren muss, damit sie auch korrekt in die DB übernommen werden.
Ist im neuen Editor nicht mehr so!

Workaround: Ohne Sonderzeichen abspeichen und dann übers Dashboard umbenennen!
