### ISSUE TITLE
Browser Eigenschaften Menue optional deaktivieren 

### ISSUE THREAD

**Issue by emb-thomas** [emb-laube/pwa#157]
Beim Arbeiten über den ie11 öffnet sich das Eigenschaften Fenster des Browsers mit, wenn ich rechtsklicke. Teilweise ist so arbeiten nicht möglich, da die Fenster sich überlappen

**Comment by emb-laube** [comment]
Habe das Rechts-Klick Menü für den IE11 deaktiviert.
@emb-thomas bitte noch ein mal kontrollieren

**Comment by emb-thomas** [comment]
Ich habe jetzt im Bearbeitungsmodus der Vorlage gar kein Menü mehr beim rechtsklick. Also auch nicht mehr das der PWA. In der Vorlagenübersicht (erste Maske) funzt es.

**Comment by emb-laube** [comment]
Damit müssen wir jetzt leider leben. Ich verwende für das Menü im Editor ein fertiges jQuery Plugin und dass kann einfach keine Unterscheidung machen...
In der Übersicht verzichte ich auf dieses Plugin und erstelle mein eigenes ContextMenu und so wird es auch im überarbeiten Editor sein. Also bis der fertig ist gibt es kein Menu.
