### ISSUE TITLE
nan Pixel

### ISSUE THREAD

**Issue by emb-thomas** [emb-laube/pwa#158]
![nanpixel](https://cloud.githubusercontent.com/assets/16306707/11815392/bdeb6638-a34b-11e5-907c-d3dcf845e9f2.jpg)

Bei vielen Vorlagen habe ich nan Pixel, anstelle der Anzeige der korrekten Anzahl

**Comment by emb-laube** [comment]
Solte behoben sein.
Eventuell muss man die Locks (Position und Größe) noch ein Mal neu setzen und anschließend abspeichern.
