### ISSUE TITLE
Hilfslinien im Bild

### ISSUE THREAD

**Issue by emb-thomas** [emb-laube/pwa#159]
fehlerhafte Hilfslinien im Bild

![hilfslinien](https://cloud.githubusercontent.com/assets/16306707/11815416/ea8c432e-a34b-11e5-9557-8613ed7e48ae.jpg)

**Comment by emb-laube** [comment]
Das hat was mit den NaN Pixeln zu tun und sollte jetzt nicht mehr vorkommen.
Siehe #158

**Comment by emb-laube** [comment]
Oha ... Nein ... Das ist ein IE11 Problem ... so eine Seuche

**Comment by emb-laube** [comment]
Der IE11 ignoriert die Einblende-Animation der Folie, daher ist die Größe und Position der Folie falsch. Zumindest für das Script ...
Und das führt dazu, dass die Positionen der Hilfslinien falsch berechnet werden. Ein Workaround ist ein Window-Resize, denn dabei werden alle Positionen neu berechnet.
Ich habe jetzt einen solchen Resize ins Script eingefügt und die Neuberechnung manuell anzustoßen.

@emb-thomas Bitte ein Mal testen!

**Comment by emb-thomas** [comment]
Habe ich und der Fehler ist in dieser Vorlage nicht mehr ersichtlich.

**Comment by emb-laube** [comment]
Super dann: Done!
