### ISSUE TITLE
Upload Mediendateien funzt net 

### ISSUE THREAD

**Issue by emb-thomas** [emb-laube/pwa#160]
Der Upload Mediendateien funzt net (Firefox), wenn man in den Vorlagen etwas hochladen will. Der Upload über den Menüpunkt aus dem Hauptmenü geht. 

![fehlerupload](https://cloud.githubusercontent.com/assets/16306707/11815484/370771f6-a34c-11e5-8f7a-92bf335e58aa.jpg)

**Comment by emb-laube** [comment]
Siehe #151
