### ISSUE TITLE
Nan Px

### ISSUE THREAD

**Issue by emb-thomas** [emb-laube/pwa#163]
![nan_pix](https://cloud.githubusercontent.com/assets/16306707/12444232/113e99bc-bf5e-11e5-98d9-ddaa208b9af0.jpg)

**Comment by emb-laube** [comment]
Obwohl schon einmal behoben, waren die Änderungen im SourceCode wieder weg ... Keine Ahnung wie das passieren konnte. Ist jetzt auf jeden Fall wieder korrigiert.
