### ISSUE TITLE
Springende Felder

### ISSUE THREAD

**Issue by emb-thomas** [emb-laube/pwa#164]
Sehr nerviger Bug, Textfelder springen nach anklicken auf andere Position. "locked" Elemente lassen sich nicht mehr "aufschließen"
![springende_texte](https://cloud.githubusercontent.com/assets/16306707/12444325/9ea1b8de-bf5e-11e5-8c6a-a345a8ad8c72.jpg)

**Comment by emb-laube** [comment]
Ja dieses "springen" ist extrem nervig!
@emb-thomas Ich habe Änderungen an den Locks und an den Textelementen gemacht. Kannst du prüfen ob es bei dir immernoch springt?
