### ISSUE TITLE
Fehler beim Laden

### ISSUE THREAD

**Issue by emb-thomas** [emb-laube/pwa#165]
![fehlerbeimladen](https://cloud.githubusercontent.com/assets/16306707/12444346/bed4f850-bf5e-11e5-9c05-fa261b086151.jpg)

Ist nur einmal aufgetreten.

**Comment by emb-laube** [comment]
Der Fehler kommt, wenn man z.B. ein Template öffnet, dass gerade von jemand anderem benutzt wird.
Das wird eigentlich geprüft, bevor die URL des Editors aufgerufen wird aber es kann passieren, dass es genau zwischen den beiden Aufrufen geschieht.
