### ISSUE TITLE
Settingsbar Felder Nachkommastellen

### ISSUE THREAD

**Issue by emb-laube** [emb-laube/pwa#21]
Nachkommastellen sollten gerundet werden, außer .5

**Comment by emb-laube** [comment]
Werte werden immer auf Integer umgerechnet!

**Comment by emb-laube** [comment]
Reopen: Referenzpunkt Mitte oder X .00005712387123987

**Comment by emb-laube** [comment]
pl_hintergrund.jpg
x: -2, y:-2, w: 1028 -> y: irgendwas mit komma!

**Comment by emb-laube** [comment]
Breite und Höhe werden jetzt auch zu Integer gerundet

**Comment by emb-baran** [comment]
checked
