### ISSUE TITLE
Fehler Load Editor

### ISSUE THREAD

**Issue by emb-laube** [emb-laube/pwa#31]
Wenn eine Folie in Benutzung ist, kommt nur die Fehlermeldung "Load Error" und es gibt keinen zurück Button.

**Comment by emb-laube** [comment]
Done!

**Comment by emb-baran** [comment]
checked: ich bekomme eine Meldung, das die Folie in benutzung ist, eine Fehlernummer und die Möglichkeit "Cancel" zu wählen
