### ISSUE TITLE
STRG + S = Quicksave

### ISSUE THREAD

**Issue by emb-laube** [emb-laube/pwa#33]

**Comment by emb-laube** [comment]
Done!

**Comment by emb-baran** [comment]
checked, aber es wird "speichern unter" aufgerufen und nicht einfach nur "speichern"!

**Comment by emb-laube** [comment]
Wenn es sich um ein neues Template/Module/Etc handelt, wir natürlich der "Speichern unter" Dialog geöffnet. Bei Bestehenden wird einfach nur gespeichert.
