### ISSUE TITLE
Hinweis individualisierte Inhalte

### ISSUE THREAD

**Issue by timemb** [emb-laube/pwa#62]
Hinweis innerhalb Präsentationen, dass diese Folie von mir (oder anderen Personen) individualisierten Inhalt enthält

**Comment by emb-laube** [comment]
Zusätzlich die Möglichkeit, die Originalen Inhalte aus dem Module neu zu laden.

**Comment by emb-laube** [comment]
Im Editor in der Slideliste Hinweis für individuellen Inhalt pro Slide

**Comment by emb-laube** [comment]
Im Presentationbrowser die Spalte Created ausblenden und dafür die Spalte Modified überarbeiten.
Datum und Uhrzeit Übersichtlicher und Hinweis für modifizierte Inhalte hinzufügen.
