### ISSUE TITLE
Preview image wird falsch aktualisiert

### ISSUE THREAD

**Issue by timemb** [emb-laube/pwa#71]
![20-07-2015 15-13-35](https://cloud.githubusercontent.com/assets/13312142/8776585/99265920-2ef2-11e5-97e3-666333265bc2.png)
im template neue shape hinzugefügt, die ein Bild überlagert und teilweise abschneidet
Previewimage des Templates aktualisiert
Previewimage des Moduls, in dem dieses Template genutzt wird, aktualisiert

Bild im Modul ausgetauscht
Previewimage des Moduls, in dem dieses Template genutzt wird, aktualisiert
Previewimage der Präsentation, in der dieses Modul genutzt wird, aktualisiert, Ebene verschwindet aber (hinter das Bild)

im Editmode ist alles OK

**Comment by timemb** [comment]
manuelles Neu-Speichern der Präsentation hat das Previewbild behoben und die Anzeige im "Online Ansehen" und bei beiden Exports behoben

**Comment by emb-laube** [comment]
Done!
