### ISSUE TITLE
Präsentation (online ansehen/ beide exports) Anordnung der Layer wie in Preview

### ISSUE THREAD

**Issue by timemb** [emb-laube/pwa#72]
Online Ansehen und Exports der Präsentation zeigt Anordnung der Layer wie im Previewimage ( siehe ISSUE #71 )

im Editmode von der Präsi wird das Previewimage temporär korrigiert, nachdem man sich die Folie anschaut. Diese korrektur des Previewimage wird nicht als Änderung des Inhalts angesehen, korrigiertes Previewimage wird beim Schließen des Editmode verworfen

**Comment by timemb** [comment]
manuelles Neu-Speichern der Präsentation hat das Previewbild behoben und die Anzeige im "Online Ansehen" und bei beiden Exports behoben

**Comment by emb-laube** [comment]
Done!
