### ISSUE TITLE
Anmeldung mit Windows Token anstatt Passwort eingeben

### ISSUE THREAD

**Issue by timemb** [emb-laube/pwa#83]
Anmeldung mit Windows Token anstatt Passwort manuell eingeben
geht das?
macht auf jeden fall sinn, so muss man sich keine PWs merken

**Comment by emb-laube** [comment]
Teschnisch nicht möglich, da der Browser bzw. JavaScript aus Sicherheitsgründen nicht auf diese Tokens zugreifen kann.
